{"level":"error","message":"에러 로그 테스트","metadata":{"error":"테스트 에러 발생","meta":{}},"stack":"Error: 테스트 에러 발생\n    at file:///Users/hj/work/Chaltteok_BE/test/logging-test.js:17:23\n    at ModuleJob.run (node:internal/modules/esm/module_job:272:25)\n    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:580:26)\n    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:98:5)","timestamp":"2025-03-28 00:29:13"}
{"level":"error","message":"에러 추적 테스트","metadata":{"error":"의도적으로 발생시킨 에러","meta":{"code":"TEST_ERROR_CODE","context":{"action":"test","userId":999}}},"stack":"Error: 의도적으로 발생시킨 에러\n    at file:///Users/hj/work/Chaltteok_BE/test/logging-test.js:53:9\n    at ModuleJob.run (node:internal/modules/esm/module_job:272:25)\n    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:580:26)\n    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:98:5)","timestamp":"2025-03-28 00:29:13"}
{"level":"error","message":"비동기 작업 중 에러 발생","metadata":{"error":"비동기 작업 실패","meta":{}},"stack":"Error: 비동기 작업 실패\n    at Timeout._onTimeout (file:///Users/hj/work/Chaltteok_BE/test/logging-test.js:70:18)\n    at listOnTimeout (node:internal/timers:614:17)\n    at process.processTimers (node:internal/timers:549:7)","timestamp":"2025-03-28 00:29:13"}
